### ISSUE TITLE
ManuallyDropArena::drop shadowed by Drop::drop

### ISSUE THREAD

**Issue by SpecificProtagonist** [taylordotfish/fixed-typed-arena#1] opened 2022-02-21 19:20 UTC
`ManuallyDropArena::drop` is supposed to be called to prevent memory leaks. Having a `&mut self`-Parameter suggests one should call it as an instance method. That however resolves to `std::ops::Drop::drop`. This is a no-op and a compile error; the suggested fix of using `std::mem::drop` is also a no-op and not what one wants.

Can the method be renamed, e.g. to `manually_drop`, to prevent this mistake?

**Comment by taylordotfish** [comment] 2022-04-22 01:26
I'm not able to reproduce this issue. There are several tests ([example](https://github.com/taylordotfish/fixed-typed-arena/blob/0.2.1/src/tests/manually_drop.rs#L39)) that call `ManuallyDropArena::drop` as an instance method, and they all pass (at least for me).

My understanding is that `ManuallyDropArena::drop` takes precedence over `Drop::drop`, since it's from an inherent implementation rather than a trait. The following minimal example also compiles successfully for me:

```rust
struct Test;

impl Drop for Test {
    fn drop(&mut self) { println!("Drop::drop"); }
}

impl Test {
    fn drop(&mut self) { println!("Test::drop"); }
}

fn main() {
    let mut t = Test;
    t.drop();
}
```

I'm able to run the above and get the expected output of `Test::drop`, followed by `Drop::drop` when `t` goes out of scope. Do you have an example where `.drop()` resolves to `Drop::drop` instead?

**Comment by SpecificProtagonist** [comment] 2022-04-22 11:42
Ah, sorry, I had the arena inside of a mutex, and tried to call `mutex_containing_the_arena.lock().unwrap().drop()`, which resolves to `Drop::drop` because `MutexGuard` impls `Drop`. I'm gonna guess the same error happens when the arena is in an `Arc`. Not a big problem, just confusing at first.

**Comment by taylordotfish** [comment] 2022-04-26 05:41
Ah, makes sense. Well, that's a good enough reason to add a differently named method anyway.

**Closed as completed** 2022-04-26 05:42 UTC
